language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_install:
- cd python
- sudo apt-get update
- sudo apt-get install -y libssl-dev
install:
- python setup.py install
script:
- python example/example.py
