language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- cd python
- sudo apt-get update
- sudo apt-get install -y libssl-dev
install:
- python setup.py install
script:
- python example/example.py
deploy:
  provider: pypi
  user: unibg-seclab
  password:
    secure: deZt5gMRJgmMD6opJULjQgWSiyeAu0Aw2Xf1Buxdz8VC5YfQ/kN4TM/4x7+rzDVuNtI6wuI3mHZl1yjvkmuuvErXI++xms7TE2Y+zHwvle/bYXIUqbpzLMHOwuM2zWpEJDNSjmb2iFxcf4Iml5MEzHiEMl8ZVVm1EiCngy4gQavJ4Y+jLk+WTZR6selTYJuR03zN3wICxEoOU5Y16QBComzgdc7YdMahpJTYlQVEArB1wOb1XVbWX4A+v/8SZQM1CK64u33EnTP5HGyLR/jIlHiTukw9TjBdLBDn9atkIbw+AavluUw/IPWBag8PcmJkN+TszZYQieLzBRl746WDPuhC4p92O2EebIL6FbLtYQxXsLwG4q1In8UO08BTU3QbXlYT4uBShjx/SV832c04xueRA0nyVEcH5uv1CBIMSGv2uDn/9B/4dqdqw78lAKZSCAa0lt8/XQhIg39P95UTkTJ65KAgFbNlcd+R0vTdvzimyZHQoY1XH26rMdXEXg2YRe+EvOcz/BWjOB54peILtMXdrJE9Aa2PIiDRciWQTcDoiHy+Tg7QRTTtuWg/9Y5A9aCOXzjNj8KiFoTD1O/Os5ZjahVFMU6897HSRIXV21EFA7oRYW3p59q5b/WUY1RztuFFXh872CGtJiN3kwy+UW6m8H3kDx881o1UGqxG/70=
  on:
    tags: true
    branch: master
