# AES variant
MINI_SIZE=32
BLOCK_SIZE=64
MINI_PER_MACRO=128

# OAEP variant
OAEP_MINI_SIZE=4
OAEP_BLOCK_SIZE=64
OAEP_MINI_PER_MACRO=4096

# if RECURSIVE_SHA512=1 then SHA512 is used as OAEP G function, otherwise AES is used
RECURSIVE_SHA512=1

# if NAOR=1 use NAOR-1999 schema
NAOR=0
NAOR_EXTERNAL_ONLY=0

# else if CAPKUN=1 use Capkun schema, otherwise use the original 3-steps OAEP
CAPKUN=1
